---
- name: Create jellyfin namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: jellyfin
- name: Apply static PV/PVC manifests
  kubernetes.core.k8s:
    state: present
    definition: "{{  lookup('template', 'video-pvc.yaml') | from_yaml_all }}"
- name: Install the Jellyfin Helm chart
  kubernetes.core.helm:
    create_namespace: true
    chart_repo_url: "https://johanneskastl.github.io/helm-charts/"
    chart_ref: "jellyfin"
    chart_version: "10.0.1"
    release_name: "jellyfin"
    release_namespace: "jellyfin"
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
