---
- name: Configure what is running on the cluster
  hosts: localhost
  roles:
    - role: kubelet_serving_cert_approver
      tags: ["kubelet_serving_cert_approver"]
      when: kubelet_serving_cert_approver_enabled
      vars:
        kubelet_serving_cert_approver_ha: "{{ ha }}"
    - role: metrics_server
      tags: ["metrics_server"]
      when: metrics_server_enabled
    - role: metallb
      tags: ["metallb"]
      when: metallb_enabled
    - role: ingress
      tags: ["ingress"]
      when: ingress_enabled
      vars:
        ingress_ha: "{{ ha }}"
    - role: cloudflare_tunnel
      tags: ["cloudflare_tunnel"]
      when: cloudflare_tunnel_enabled
      vars:
        cloudflare_tunnel_ha: "{{ ha }}"
    - role: local_path_provisioner
      tags: ["local_path_provisioner"]
      when: local_path_provisioner_enabled
    - role: democratic_csi
      tags: ["democratic_csi"]
      when: democratic_csi_enabled
    - role: minio
      tags: ["minio"]
      when: minio_enabled
    - role: pgo
      tags: ["pgo"]
      when: pgo_enabled
    - role: authentik
      tags: ["authentik"]
      when: authentik_enabled
    - role: prometheus
      tags: ["prometheus"]
      when: prometheus_enabled
      vars:
        prometheus_alertmanager_ingressclass: "external"
        prometheus_grafana_ingressclass: "external"
    - role: jellyfin
      tags: ["jellyfin"]
      when: jellyfin_enabled
