---
- name: Configure what is running on the cluster
  hosts: localhost
  roles:
   - role: kubelet_serving_cert_approver
     tags: ["kubelet_serving_cert_approver"]
   - role: metrics_server
     tags: ["metrics_server"]
   - role: metallb
     tags: ["metallb"]
   - role: democratic_csi
     tags: ["democratic_csi"]
   - role: pgo
     tags: ["pgo"]
