---
- name: Reset the admin user password in teleport
  hosts: localhost
  tasks:
    - name: Get teleport-cluster-auth pod name
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "teleport-cluster"
        label_selectors:
          - "app.kubernetes.io/component=auth"
      register: teleport_cluster_auth_pods
    - name: Reset admin user account
      kubernetes.core.k8s_exec:
        namespace: teleport-cluster
        pod: "{{ teleport_cluster_auth_pods.resources[0].metadata.name }}"
        command: tctl users reset admin --ttl 10m
      register: teleport_cluster_admin_reset_result
    - name: Report admin reset URL
      ansible.builtin.debug:
        msg: "{{ teleport_cluster_admin_reset_result.stdout_lines[1] }}"
