---
- name: Create democratic-csi namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: democratic-csi
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
- name: Install the democratic-csi Helm chart
  kubernetes.core.helm:
    chart_repo_url: "https://democratic-csi.github.io/charts"
    chart_ref: "democratic-csi"
    chart_version: "0.14.2"
    release_name: "{{ item }}-democratic-csi"
    release_namespace: "democratic-csi"
    values: "{{ lookup('template', item + '-values.yaml') | from_yaml }}"
  loop:
    - "nfs"
    - "iscsi"
