ungrouped:
  hosts:
    localhost:
      ansible_connection: local
      ha: false
      kubelet_serving_cert_approver_enabled: true
      metrics_server_enabled: false # rancher-desktop installs metrics server by default
      metallb_enabled: false
      ingress_enabled: true
      ingress_base_url:
        dev: "chickencoup.net"
      local_path_provisioner_enabled: false # Already installed by k3s
      democratic_csi_enabled: false # No ZFS server available locally
      minio_enabled: true
      pgo_enabled: true
      prometheus_enabled: true
      prometheus_alertmanager_ingressclass: "dev"
      prometheus_grafana_ingressclass: "dev"
