---
- name: Install the CloudNativePG Helm chart
  kubernetes.core.helm:
    chart_repo_url: "https://cloudnative-pg.github.io/charts"
    chart_ref: "cloudnative-pg"
    chart_version: "v0.19.1"
    release_name: "cnpg"
    release_namespace: "cnpg"
    create_namespace: true
