---
- name: Install the Adguard Home Helm chart
  kubernetes.core.helm:
    create_namespace: true
    chart_repo_url: "https://helm-charts.rm3l.org"
    chart_ref: "adguard-home"
    chart_version: "0.11.0"
    release_name: "adguard"
    release_namespace: "adguard"
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
