---
csiDriver:
  name: "iscsi"
storageClasses:
  - name: iscsi
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4
      detachedVolumesFromSnapshots: "false"
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:
volumeSnapshotClasses:
  - name: iscsi
    parameters:
      detachedSnapshots: "true"
driver:
  config:
    driver: freenas-api-iscsi
    httpConnection:
      protocol: https
      host: e14s-5wr04w1.jdmarble.net
      apiKey: "{{democratic_csi_freenas_apikey}}"
    zfs:
      datasetParentName: "front/jdmarble-net-iscsi/v"
      detachedSnapshotsDatasetParentName: "front/jdmarble-net-iscsi/s"
    iscsi:
      targetPortal: "e14s-5wr04w1.jdmarble.net"
      namePrefix: "csi-"
      nameSuffix: "-"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
node:
  hostPID: true
  driver:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /usr/local/etc/iscsi
    iscsiDirHostPathType: ""
