---
env:
  TZ: "America/Los Angeles"
  JELLYFIN_PublishedServerUrl: "http://jellyfin.jdmarble.net"
image:
  tag: "10.8.12"
service:
  main:
    type: LoadBalancer
    #ports:
    #  http:
    #    port: 80
    loadBalancerIP: "192.168.2.129"
persistence:
  config:
    enabled: true
  media:
    enabled: true
    type: nfs
    server: e14s-5wr04w1.jdmarble.net
    path: /mnt/front/video
