---
env:
  TZ: "America/Los Angeles"
  JELLYFIN_PublishedServerUrl: "http://jellyfin.jdmarble.net"
image:
  tag: "10.8.12"
ingress:
  main:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - host: jellyfin.jdmarble.net
        paths:
          - path: /
persistence:
  config:
    enabled: true
  media:
    enabled: true
    type: nfs
    server: e14s-5wr04w1.jdmarble.net
    path: /mnt/front/video
