---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-video
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: video
    volumeAttributes:
      server: e14s-5wr04w1.jdmarble.net
      share: /mnt/front/video
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jellyfin
  name: media-video
spec:
  storageClassName: ""
  volumeName: media-video
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
