---
- name: Get the kubelet-serving-cert-approver manifests
  ansible.builtin.uri:
    url: "https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/\
      v{{ kubelet_serving_cert_approver_version }}/deploy/\
      {{ kubelet_serving_cert_approver_ha | ternary('ha', 'standalone') }}-install.yaml"
    return_content: true
  register: kubelet_serving_cert_approver_manifests
- name: Verify the kubelet-serving-cert-approver manifests hash
  ansible.builtin.assert:
    that:
      - kubelet_serving_cert_approver_sha256 == kubelet_serving_cert_approver_manifests.content | hash("sha256")
- name: Create kubelet-serving-cert-approver namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ kubelet_serving_cert_approver_namespace }}"
- name: Install kubelet-serving-cert-approver manifests
  kubernetes.core.k8s:
    state: present
    definition: "{{ kubelet_serving_cert_approver_manifests.content | ansible.builtin.from_yaml_all }}"
