---
clusterName: teleport.jdmarble.net
kubeClusterName: jdmarble.net
authentication:
  type: local
acme: true
acmeEmail: jdmarble@jdmarble.com
service:
  spec:
    loadBalancerIP: 192.168.2.128
persistence:
  volumeSize: 1Gi
proxy:
  teleportConfig:
    teleport:
      auth_server: teleport-cluster-auth:3025
proxyProtocol: "off"
extraArgs:
  - "--bootstrap=/bootstrap/bootstrap.yaml"
extraVolumes:
  - name: bootstrap
    configMap:
      name: bootstrap
extraVolumeMounts:
  - name: bootstrap
    mountPath: /bootstrap
