---
prometheus-node-exporter:
  namespaceOverride: "node-exporter" # Needs to be in a priviledged namespace
grafana:
  grafana.ini:
    analytics:
      reporting_enabled: false
      check_for_updates: false
      check_for_plugin_updates: false
      feedback_links_enabled: false
    security:
      admin_user: jdmarble
      admin_email: jdmarble@jdmarble.com
    users:
      allow_sign_up: false
      auto_assign_org: true
    auth.jwt:
      # Adapted from https://gist.github.com/mhr3/f741ffa71f4dfa0152a6020758042c32
      enabled: true
      auto_sign_up: true
      disable_signout_menu: true
      username_claim: email
      email_claim: email
      jwk_set_url: "https://jdmarble.cloudflareaccess.com/cdn-cgi/access/certs"
      header_name: "Cf-Access-Jwt-Assertion"
